experiment:
  name: "deep_learning"
  seed: 42
  device: "cuda"

model:
  # add as needed

dataset:
  name: "Food101" # either Food101 or Flowers102
  path: "ob"
  batch_size: 128
  val_batch_size: 512
  train_split: 0.8

training:
  epochs: 80
  learning_rate: 1e-4
  patience: 5
  early_stopping: true

optimizer:
  type: "Adam"
  weight_decay: 1e-6

lr_scheduler:
  factor: 0.1
  min_lr: 1e-5

logging:
  wandb:
    project: "deep_learning"
    enabled: false