experiment:
  name: "deep_learning"
  seed: 42
  device: "cuda"

model:
  # add as needed

dataset:
  name: "Food101" # either Food101 or Flowers102 or DTD047
  path: "ob"
  batch_size: 128
  val_batch_size: 512
  subset_weight: 0.25

training:
  from_pretrained: False
  epochs: 50
  learning_rate: 1e-4
  patience: 5
  early_stopping: false
  num_epochs_mix: 2
  mix_for_only_one: true
  num_layers_frozen: 0
  num_bad_classes: 25

logging:
  wandb:
    project: "deep_learning"
    enabled: true

optimizer:
  type: "Adam"
  weight_decay: 1e-6

lr_scheduler:
  factor: 0.1
  min_lr: 1e-5