defaults:

experiment:
  name: "deep_learning"
  seed: 42
  device: "cuda"

model:
  # add as needed

dataset:
  name: "CIFAR10"
  path: "ob"
  batch_size: 64
  num_workers: 4
  train_split: 0.8

training:
  epochs: 100
  learning_rate: 1e-3
  patience: 10
  early_stopping: true
  metric_to_monitor: "val_accuracy"

optimizer:
  type: "Adam"
  weight_decay: 1e-5
  betas: [0.9, 0.999]

lr_scheduler:
  factor: 0.1
  patience: 5
  min_lr: 1e-5

logging:
  wandb:
    project: "deep_learning"
    entity: "orionfoo" #change to your wandb username i believe?
    enabled: true